export enum Language {
  EN = "en-US",
  ZH = "zh-CN",
}

// 语言枚举
export enum Lang {
  EN = "en",
  ZH = "zh",
  ES = "es",
  FR = "fr",
  DE = "de",
  IT = "it",
  JA = "ja",
  KO = "ko",
  PT = "pt",
  RU = "ru",
  AR = "ar",
  TR = "tr",
  NL = "nl",
  SV = "sv",
  DA = "da",
  NO = "no",
  FI = "fi",
  EL = "el",
  HI = "hi",
  PL = "pl",
  HU = "hu",
  CS = "cs",
  SK = "sk",
  TH = "th",
  ID = "id",
  VI = "vi",
  RO = "ro",
  HR = "hr",
}

// 语言对象
export const languages: { [key in Lang]: { chineseName: string; englishName: string } } = {
  [Lang.EN]: { chineseName: "英语", englishName: "English" },
  [Lang.ZH]: { chineseName: "中文", englishName: "Chinese" },
  [Lang.ES]: { chineseName: "西班牙语", englishName: "Spanish" },
  [Lang.FR]: { chineseName: "法语", englishName: "French" },
  [Lang.DE]: { chineseName: "德语", englishName: "German" },
  [Lang.IT]: { chineseName: "意大利语", englishName: "Italian" },
  [Lang.JA]: { chineseName: "日语", englishName: "Japanese" },
  [Lang.KO]: { chineseName: "韩语", englishName: "Korean" },
  [Lang.PT]: { chineseName: "葡萄牙语", englishName: "Portuguese" },
  [Lang.RU]: { chineseName: "俄语", englishName: "Russian" },
  [Lang.AR]: { chineseName: "阿拉伯语", englishName: "Arabic" },
  [Lang.TR]: { chineseName: "土耳其语", englishName: "Turkish" },
  [Lang.NL]: { chineseName: "荷兰语", englishName: "Dutch" },
  [Lang.SV]: { chineseName: "瑞典语", englishName: "Swedish" },
  [Lang.DA]: { chineseName: "丹麦语", englishName: "Danish" },
  [Lang.NO]: { chineseName: "挪威语", englishName: "Norwegian" },
  [Lang.FI]: { chineseName: "芬兰语", englishName: "Finnish" },
  [Lang.EL]: { chineseName: "希腊语", englishName: "Greek" },
  [Lang.HI]: { chineseName: "印地语", englishName: "Hindi" },
  [Lang.PL]: { chineseName: "波兰语", englishName: "Polish" },
  [Lang.HU]: { chineseName: "匈牙利语", englishName: "Hungarian" },
  [Lang.CS]: { chineseName: "捷克语", englishName: "Czech" },
  [Lang.SK]: { chineseName: "斯洛伐克语", englishName: "Slovak" },
  [Lang.TH]: { chineseName: "泰语", englishName: "Thai" },
  [Lang.ID]: { chineseName: "印度尼西亚语", englishName: "Indonesian" },
  [Lang.VI]: { chineseName: "越南语", englishName: "Vietnamese" },
  [Lang.RO]: { chineseName: "罗马尼亚语", englishName: "Romanian" },
  [Lang.HR]: { chineseName: "克罗地亚语", englishName: "Croatian" },
};
